"""add new values

Revision ID: 02c877e5897f
Revises: b9f78b2b5cdd
Create Date: 2020-09-17 14:46:36.697335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c877e5897f'
down_revision = 'b9f78b2b5cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
