"""add new values

Revision ID: 58c2bd55c72e
Revises: 5ed625ddd4df
Create Date: 2020-09-16 22:37:44.550215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c2bd55c72e'
down_revision = '5ed625ddd4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
