"""add new values

Revision ID: 9e993d72426b
Revises: e4b85c2ef48c
Create Date: 2020-09-16 23:07:17.092381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e993d72426b'
down_revision = 'e4b85c2ef48c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('full_name', sa.String(), nullable=True))
    op.drop_column('contacts', 'fullname')
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'full_name')
    op.add_column('contacts', sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'full_name')
    # ### end Alembic commands ###
