"""add new values

Revision ID: a21d6ce824bd
Revises: ff2729eb792e
Create Date: 2020-09-16 22:05:17.243638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21d6ce824bd'
down_revision = 'ff2729eb792e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contact',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('contact', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('fullname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'Contact', ['contact'], ['id'])
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'yy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yy', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'fullname')
    op.drop_column('users', 'contact')
    op.drop_column('users', 'age')
    op.drop_table('Contact')
    # ### end Alembic commands ###
