"""add new values

Revision ID: b9f78b2b5cdd
Revises: 9e993d72426b
Create Date: 2020-09-17 10:24:36.690107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f78b2b5cdd'
down_revision = '9e993d72426b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
