"""add new values

Revision ID: c5bc85265494
Revises: a21d6ce824bd
Create Date: 2020-09-16 22:07:59.461315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5bc85265494'
down_revision = 'a21d6ce824bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Contact')
    op.drop_constraint('users_contact_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'contacts', ['contact'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_contact_fkey', 'users', 'Contact', ['contact'], ['id'])
    op.create_table('Contact',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('nextval(\'"Contact_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Contact_pkey')
    )
    op.drop_table('contacts')
    # ### end Alembic commands ###
