"""add new values

Revision ID: e4b85c2ef48c
Revises: 58c2bd55c72e
Create Date: 2020-09-16 22:50:33.441904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b85c2ef48c'
down_revision = '58c2bd55c72e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'contacts', ['contact'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'contact')
    # ### end Alembic commands ###
