"""add users table

Revision ID: ff2729eb792e
Revises: db96c8c5edd2
Create Date: 2020-09-16 16:45:04.314173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2729eb792e'
down_revision = 'db96c8c5edd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yy', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'yy')
    # ### end Alembic commands ###
